spring.application.name=to-do-list-api

server.port = 8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/task_tracker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.flyway.locations=classpath:db/migration/mysql

#spring.flyway.url=jdbc:mysql://localhost:3306/task_tracker
#spring.flyway.username=root
#spring.flyway.password=password

spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=update

# === Root level ===
logging.level.root=INFO

# === Spring ===
logging.level.org.springframework=INFO
logging.level.org.springframework.web=DEBUG

# === Hibernate (SQL & params) ===
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# === Your application ===
logging.level.com.example.to_do_list_api=DEBUG


jwt.key=YzEyMzR0bXZxQzRmNTZ2cEFoUGVpMWdIajU3aWdoZ2g
